config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resources :orders
  resources :meals, only: [:new, :create]
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout

end

app/models/meal.rb
class Meal < ActiveRecord::Base
  belongs_to :order
  belongs_to :client, class_name: 'User'

  validates :name,  presence: true
  validates :price, presence: true
  validate { |meal| MealValidator.new(meal).validate }
end

app/models/meal_validator.rb
class MealValidator
  def initialize(meal)
    @meal = meal
  end

  def validate
    @meal.errors[:base] << 'You can book only one meal per order' if user_has_meal_in_order?
    @meal.errors[:base] << 'You can book meal only when order has booking status' unless order_has_booking_status?
    @meal.errors[:base] << 'You can not book a meal in deleted order' if order_was_deleted?
  end

  private

  def user_has_meal_in_order?
    user_id  = @meal.client_id
    order_id = @meal.order_id
    order    = Order.find(order_id)

    User.find(user_id).meals.map(&:order).include?(order)
  end

  def order_has_booking_status?
    @meal.order.status == 'booking'
  end

  def order_was_deleted?
    @meal.order.deleted?
  end
end

app/models/order.rb
require 'uri'

class Order < ActiveRecord::Base
  belongs_to :creator, class_name: 'User'
  has_many   :meals

  STATUS = %w(booking finalized ordered delivered).freeze

  validates :restaurant_name, presence:  true
  validates :restaurant_link, format:    { with: /\A#{URI.regexp(%w(http https))}\z/ }
  validates :status,          inclusion: { in: STATUS }

  scope :deleted,     -> { where.not(deleted_at: nil) }
  scope :not_deleted, -> { where(deleted_at: nil) }

  scope :active,  -> { where(status: 'booking').not_deleted }
  scope :history, -> { where('status!=? OR deleted_at IS NOT NULL', 'booking') }

  def deleted?
    deleted_at != nil
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :meals,  foreign_key: 'client_id',  class_name: 'Meal'
  has_many :orders, foreign_key: 'creator_id', class_name: 'Order'

  validates :provider, :uid, :name, presence: true

  def self.find_or_create_from_auth_hash(auth_hash)
    where(provider: auth_hash.provider, uid: auth_hash.uid, name: auth_hash.info.name).first_or_create
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  private

  def user_signed?
    !current_user.nil?
  end

  def access_denied
    redirect_to root_path, notice: "To access this page You must be logged in"
  end

  def authorize!
    access_denied unless user_signed?
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :authorize!

  def new
    @meal     = Meal.new
    @order_id = order_id_params.to_i
  end

  def create
    @meal = current_user.meals.new(meal_params)
    if @meal.save
      redirect_to orders_path
    else
      render :new
    end
  end

  private

  def order_id_params
    params.require(:order_id)
  end

  def meal_params
    params.require(:meal).permit(:name, :price, :order_id)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authorize!

  def index
    @active_orders  = OrderQuery.new.active
    @history_orders = OrderQuery.new.history
  end

  def new
    @order = Order.new
  end

  def create
    @order = current_user.orders.new(order_params)
    if @order.save
      redirect_to orders_path
    else
      render :new
    end
  end

  private

  def order_params
    params.require(:order).permit(:restaurant_name, :restaurant_link, :status)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_or_create_from_auth_hash(auth_hash)
    session[:user_id] = @user.id
    redirect_to orders_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

    %link{:href => "http://fonts.googleapis.com/css?family=Lato:regular,bold", :rel => "stylesheet", :type => "text/css"}
    %title MealOrdering

  %body
    .container
      - if current_user
        %ul.user_logging
          %li= current_user.name
          %li= link_to "| Log out", logout_path

      %h1 Meal Ordering

      = yield

app/views/meals/new.html.haml
%h2 Book a meal

= render partial: 'shared/error_messages', locals: {item: @meal}

= form_for(@meal) do |f|
  = f.label :name
  = f.text_field :name
  %br
  = f.label :price
  = f.number_field :price
  %br
  = f.hidden_field :order_id, value: @order_id

  = f.submit 'Create!'

= link_to 'Back to the main page', orders_path

app/views/orders/index.html.haml
%h2 Orders
%ul
  - @active_orders.each do |order|
    %li= link_to order.restaurant_name, order.restaurant_link, target: '_blank'
    %ul
      - order.meals.each do |meal|
        %li #{meal.name} | #{meal.price}
      %li= link_to 'order a meal for yourself', new_meal_path(order_id: order.id)



%h3 History of orders
%ul
  - @history_orders.each do |order|
    %li= link_to order.restaurant_name, order.restaurant_link, target: '_blank'
    %ul
      - order.meals do |meal|
        %li #{meal.name} | #{meal.price}

.new_order
  = link_to '...or create a new order', new_order_path

app/views/orders/new.html.haml
%h2 Create a new order

= render partial: 'shared/error_messages', locals: {item: @order}

= form_for(@order) do |f|
  = f.label :restaurant_name
  = f.text_field :restaurant_name
  %br
  = f.label :restaurant_link
  = f.url_field :restaurant_link
  %br
  = f.label :status
  = f.select(:status, options_for_select(Order::STATUS), selected: 'booking')
  %br
  = f.submit 'Create!'

= link_to 'Back to the main page', orders_path

app/views/shared/_error_messages.html.haml
- if item.errors.any?
  .error_messages
    %h2 The form contains #{pluralize(item.errors.count, 'error')}
    %ul
    - item.errors.full_messages.each do |msg|
      %li #{msg}